extra: make sure errors go to stderr

diff --git a/extra/virtualenv b/extra/virtualenv
--- a/extra/virtualenv
+++ b/extra/virtualenv
@@ -17,7 +17,7 @@ function v() {
 		export VIRTUAL_ENV=$1
 		hash -r
 	else
-		echo "virtualenv $1 not found"
+		echo >&2 "virtualenv $1 not found"
 		return 1
 	fi
 }
@@ -25,7 +25,7 @@ function v() {
 function d() {
 	if [ -z "${oldpath}" ]
 	then
-		echo "no virtualenv active"
+		echo >&2 "no virtualenv active"
 		return 1
 	fi
 	export PATH=${oldpath}
@@ -38,7 +38,7 @@ function mkv() {
 	test -d ${VIRTUALENVS} || mkdir -p ${VIRTUALENVS}
 	if [ -z "${1}" ]
 	then
-		echo "Please specify the name of the virtualenv you want to create"
+		echo >&2 "Please specify the name of the virtualenv you want to create"
 		return 2
 	fi
 	python=${PYTHON:-python3}
@@ -49,7 +49,7 @@ function mkv() {
 function rmv() {
 	if [ -z "${1}" ]
 	then
-		echo "Please specify the virtualenv you want to remove"
+		echo >&2 "Please specify the virtualenv you want to remove"
 		return 2
 	fi
 	dir=${VIRTUALENVS}/${1}
